apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30072
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672
  selector:
    app: rabbitmq
